# Generated by Django 5.2.5 on 2025-08-22 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_options_alter_article_date_publication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='auteur',
            field=models.CharField(default='Admin', max_length=150),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='articles/videos/')),
                ('url', models.URLField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='blog.article')),
            ],
        ),
    ]
